Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CSharp_ProductsCategories.Models
{
    public class Category
    {
        [Key]
        public int CategoryId {get;set;}
        public string Name {get;set;}
        public List<Association> AssociatedProducts {get;set;} 
        public DateTime CreatedAt {get;set;} = DateTime.Now;
        public DateTime UpdatedAt {get;set;} = DateTime.Now;
        
    }
}

Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using CSharp_ProductsCategories.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CSharp_ProductsCategories.Controllers
{
    public class CategoryController : Controller
    {
        private ProCatContext _db; 
        public CategoryController(ProCatContext context) 
        { 
            _db = context; 
        } 

        [HttpGet("categories")]
        public IActionResult AllCategories()
        {
            List<Category> allCategories = _db.Categories.Include(cat => cat.AssociatedProducts).ThenInclude(a => a.Product).ToList();

            return View(new ViewAndCreateCategory{Categories = allCategories});
        }

        // [HttpPost("")]
        public IActionResult CreateCategory(ViewAndCreateCategory newViewAndCreateCategoryCat)
        {
            _db.Categories.Add(newViewAndCreateCategoryCat.Category);
            _db.SaveChanges();

            return RedirectToAction("AllCategories");
        }

        [HttpGet("{CatName}/{CatId}")]
        //these params were passed from  asp-route-[] , the variable names have to match asp-route-[whatever]
        public IActionResult ViewSingleCategory(int CatId)
        //the int was passed from  asp-route-[] , the variable name has to match asp-route-[whatever]
        {   
            Category toView = GetCompleteCategory(CatId);
            // _db.Categories.Include(c => c.AssociatedProducts).ThenInclude(a => a.Category).FirstOrDefault(cat => cat.CategoryId == CatId);

            ViewCategoryDetails toViewDetails = new ViewCategoryDetails{ CurrentCategory = toView};

            ViewBag.AssociatedPros = _db.Categories.Include(cat => cat.AssociatedProducts).ThenInclude(a => a.Product).Where(c => c.CategoryId == CatId).ToList();
            
            ViewBag.UnAssociatedPros = _db.Products.Include(p => p.AssociatedCategories).ThenInclude(a => a.Category).Where(pro => pro.AssociatedCategories.All(a => a.CategoryId != CatId));

            // ViewBag.UnAssciatedPros = 
            return View(toViewDetails);
        }

        [HttpPost("AddProToCat")]
        public IActionResult AddProToCat(ViewCategoryDetails newViewCategoryDetail)
        {
            int ProductId = newViewCategoryDetail.Association.ProductId;
            int CategoryId = newViewCategoryDetail.Association.CategoryId;

            Category CurrCat = _db.Categories.FirstOrDefault(c => c.CategoryId == CategoryId);

            // Product toAddPro = _db.Products.FirstOrDefault(p => p.ProductId == ProductId);

            if(ProductId == 0)
            {
                TempData["alertMessage"] = "<p style='color:red;'>Please choose a product.</p>";

                return RedirectToAction("ViewSingleCategory", new{CatId = CategoryId, CatName =CurrCat.Name});
            }

            Association newAssociation = new Association{
                ProductId = ProductId ,
                CategoryId = CategoryId
            };
            
            _db.Associations.Add(newAssociation);
            _db.SaveChanges();


            return RedirectToAction("ViewSingleCategory", new{CatId = CategoryId, CatName =CurrCat.Name});

        }

        public Category GetCompleteCategory (int CatId) {
            Category retrievedCategory = _db.Categories
                .FirstOrDefault(cat => cat.CategoryId == CatId);
            HttpContext.Session.SetInt32("CategoryId", CatId);

            return retrievedCategory;
        }

    }
}

Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using CSharp_ProductsCategories.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CSharp_ProductsCategories.Controllers
{
    public class ProductController : Controller
    {        
        private ProCatContext _db; 
        public ProductController(ProCatContext context) 
        { 
            _db = context; 
        } 

        [HttpGet("products")]
        public IActionResult AllProducts()
        {
            List<Product> products= _db.Products.Include(p => p.AssociatedCategories).ThenInclude(a => a.Product).ToList();

            CreateAndAllProducts info = new CreateAndAllProducts{AllProducts = products};
            return View(info);
        }

        [HttpPost("create")]
        public IActionResult CreateProduct(CreateAndAllProducts newCreateAndAllProducts)
        {
            _db.Products.Add(newCreateAndAllProducts.Product);
            _db.SaveChanges();

            return RedirectToAction("AllProducts");
        }

        [HttpGet("product/{ProName}/{ProId}")]
        public IActionResult ViewOneProduct(int ProId)
        {
            Product toViewPro = GetAProduct(ProId);

            ViewBag.thisProduct =  _db.Products.Include(pro => pro.AssociatedCategories).ThenInclude(a => a.Category).Where(p => p.ProductId == ProId);

            List<Category> allUnassociated =  _db.Categories.Include(cat => cat.AssociatedProducts).Where(c => c.AssociatedProducts.All(a => a.ProductId != ProId )).ToList();

            ProductDetails details = new ProductDetails{Product = toViewPro,UnAssociatedCategories = allUnassociated};
            return View(details);
        }

        public Product GetAProduct(int ProId)
        {
            Product RetrievedProduct = _db.Products.FirstOrDefault(p => p.ProductId == ProId);

            return RetrievedProduct;
        }

        [HttpPost("AddCat")]
        public IActionResult AddCatToPro(ProductDetails newProductDetails)
        {

            int ProId = newProductDetails.Association.ProductId;
            Product CurrProduct = _db.Products.FirstOrDefault(p => p.ProductId == ProId);
            
            int CatId = newProductDetails.Association.CategoryId;

            if(CatId == 0)
            {
                TempData["Message"] = "<p style='color:red;'>Please choose a category.</p>";

                return RedirectToAction("ViewOneProduct", new{ProId = ProId, ProName = CurrProduct.Name});

            }
            else{

            Association newAssociation = new Association{
                ProductId = ProId,
                CategoryId = CatId
            };

            _db.Associations.Add(newAssociation);
            _db.SaveChanges();
            }

            return RedirectToAction("ViewOneProduct", new{ProId = ProId, ProName = CurrProduct.Name});
        }


    }
}

Views/Category/AllCategories.cshtml
@model ViewAndCreateCategory

<h3 class="text-center"><a asp-action="AllProducts" asp-controller="Product" class="text-center">Got to Products</a> | <a asp-action="AllCategories" asp-controller="Category" class="text-center text-info">Got to Categories</a></h3>


<div class="container">
  <div class="row">

    <div class="col-sm-3 col-md-6">
        <div class="text-center">
          <h4 class="text-info">Add New Category</h4>
            <form asp-action="CreateCategory" asp-controller="Category" class="form-group">
            <label asp-for="Category.Name" ></label>
            <input asp-for="Category.Name" type="text">

            <input type="submit" class="btn btn-warning">
        </form>
        </div>
    </div>
    
    <div class="col-sm-9 col-md-6">
      <h4 class="text-info">Existing Categories</h4>

        @foreach (Category cat in Model.Categories)
      {
        <a asp-action="ViewSingleCategory" asp-controller="Category"  asp-route-CatName="@cat.Name" asp-route-CatId="@cat.CategoryId"
        >@cat.Name | Category ID: @cat.CategoryId  | Associated Pro: @cat.AssociatedProducts.Count</a><br>
        // Alternatively // <a href="/@cat.Name/@cat.CategoryId">@cat.Name </a> 
      }

    </div>
    @* <div class="w-100"></div> *@

  </div>
</div>

Views/Category/ViewSingleCategory.cshtml
@model ViewCategoryDetails

<h3 class="text-center"><a asp-action="AllProducts" asp-controller="Product" class="text-center">Got to Products</a> | <a asp-action="AllCategories" asp-controller="Category" class="text-center text-info">Got to Categories</a></h3>

<h1 class="text-center">@Model.CurrentCategory.Name | ID: @Model.CurrentCategory.CategoryId</h1>


<div class="container">
    <div class="row">

        <div class="col-sm-3 col-md-6">
            <p>Products in this category</p>

            @foreach (var cat in ViewBag.AssociatedPros)
            { 
                @* <p>@cat.AssociatedProducts.Count</p> *@
                @foreach (var p in cat.AssociatedProducts)
                {
                    <a asp-action="ViewOneProduct" asp-controller="Product" asp-route-ProName="@p.Product.Name" asp-route-ProId="@p.Product.ProductId" >@p.Product.Name</a><br>
                } 
            }  

        </div>
@* ~~end of left page (all products in this category~~~*@

        <div class="col-sm-3 col-md-6">
            <h3>Add Product to this category</h3>
            
            <form asp-action="AddProToCat" asp-controller="Category" method="POST"  >
                <select asp-for="Association.ProductId">
                    <option value="0">select one</option>
                @foreach (var pro in ViewBag.UnAssociatedPros)
                {
                    <option value="@pro.ProductId">@pro.Name @pro.ProductId</option>
                }
                <input type="hidden" asp-for="Association.CategoryId" value="@Model.CurrentCategory.CategoryId">

                <input  type="submit" value="Add to Category">
                @Html.Raw(TempData["alertMessage"])

                </select>
            </form>
        </div>

    </div>
</div>